
package calculadora;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CalculadoraWS", targetNamespace = "http://CalculadoraWSApplication/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CalculadoraWS {


    /**
     * 
     * @param intB
     * @param intA
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "addition", targetNamespace = "http://CalculadoraWSApplication/", className = "calculadora.Addition")
    @ResponseWrapper(localName = "additionResponse", targetNamespace = "http://CalculadoraWSApplication/", className = "calculadora.AdditionResponse")

    @Action(input = "http://CalculadoraWSApplication/CalculadoraWS/additionRequest", output = "http://CalculadoraWSApplication/CalculadoraWS/additionResponse")
    public String addition(
        @WebParam(name = "intA", targetNamespace = "")
        int intA,
        @WebParam(name = "intB", targetNamespace = "")
        int intB);

    /**
     * 
     * @param intB
     * @param intA
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "division", targetNamespace = "http://CalculadoraWSApplication/", className = "calculadora.Division")
    @ResponseWrapper(localName = "divisionResponse", targetNamespace = "http://CalculadoraWSApplication/", className = "calculadora.DivisionResponse")
    @Action(input = "http://CalculadoraWSApplication/CalculadoraWS/divisionRequest", output = "http://CalculadoraWSApplication/CalculadoraWS/divisionResponse")
    public String division(
        @WebParam(name = "intA", targetNamespace = "")
        int intA,
        @WebParam(name = "intB", targetNamespace = "")
        int intB);

    /**
     * 
     * @param intB
     * @param intA
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "multiplication", targetNamespace = "http://CalculadoraWSApplication/", className = "calculadora.Multiplication")
    @ResponseWrapper(localName = "multiplicationResponse", targetNamespace = "http://CalculadoraWSApplication/", className = "calculadora.MultiplicationResponse")
    @Action(input = "http://CalculadoraWSApplication/CalculadoraWS/multiplicationRequest", output = "http://CalculadoraWSApplication/CalculadoraWS/multiplicationResponse")
    public String multiplication(
        @WebParam(name = "intA", targetNamespace = "")
        int intA,
        @WebParam(name = "intB", targetNamespace = "")
        int intB);

    /**
     * 
     * @param intB
     * @param intA
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "substraction", targetNamespace = "http://CalculadoraWSApplication/", className = "calculadora.Substraction")
    @ResponseWrapper(localName = "substractionResponse", targetNamespace = "http://CalculadoraWSApplication/", className = "calculadora.SubstractionResponse")
    @Action(input = "http://CalculadoraWSApplication/CalculadoraWS/substractionRequest", output = "http://CalculadoraWSApplication/CalculadoraWS/substractionResponse")
    public String substraction(
        @WebParam(name = "intA", targetNamespace = "")
        int intA,
        @WebParam(name = "intB", targetNamespace = "")
        int intB);

}
