
package alarma;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Alerta", targetNamespace = "http://alarma.mycompany.com/", wsdlLocation = "http://localhost:4569/servicioAlarma?wsdl")
public class Alerta
    extends Service
{

    private final static URL ALERTA_WSDL_LOCATION;
    private final static WebServiceException ALERTA_EXCEPTION;
    private final static QName ALERTA_QNAME = new QName("http://alarma.mycompany.com/", "Alerta");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:4569/servicioAlarma?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ALERTA_WSDL_LOCATION = url;
        ALERTA_EXCEPTION = e;
    }

    public Alerta() {
        super(__getWsdlLocation(), ALERTA_QNAME);
    }

    public Alerta(WebServiceFeature... features) {
        super(__getWsdlLocation(), ALERTA_QNAME, features);
    }

    public Alerta(URL wsdlLocation) {
        super(wsdlLocation, ALERTA_QNAME);
    }

    public Alerta(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ALERTA_QNAME, features);
    }

    public Alerta(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Alerta(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Alarma
     */
    @WebEndpoint(name = "AlarmaPort")
    public Alarma getAlarmaPort() {
        return super.getPort(new QName("http://alarma.mycompany.com/", "AlarmaPort"), Alarma.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Alarma
     */
    @WebEndpoint(name = "AlarmaPort")
    public Alarma getAlarmaPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://alarma.mycompany.com/", "AlarmaPort"), Alarma.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ALERTA_EXCEPTION!= null) {
            throw ALERTA_EXCEPTION;
        }
        return ALERTA_WSDL_LOCATION;
    }

}
